[project]
name = "whisper_streaming_web"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]==0.115.5",
    "faster-whisper==1.1.1",
    "ffmpeg-python==0.2.0",
    "uvicorn==0.34.0",
    "librosa==0.10.2.post1",
    "soundfile==0.13.1"
]